on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker/login-action@v1
      with:
        registry: quay.io
        username: alexpdp7+gh_talos_check_builder
        password: ${{ secrets.QUAY_IO_SECRET }}
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    - uses: docker/build-push-action@v2
      with:
        registry: quay.io
        username: alexpdp7+gh_talos_check_builder
        password: ${{ secrets.QUAY_IO_SECRET }}
        tags: quay.io/alexpdp7/talos-check:latest
        push: true
        file: Containerfile
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
